const books = [
    {
      "id": 1,
      "title": "Atomic Habits",
      "author": "James Clear",
      "category": "Self Help",
      "price": 499,
      "rating": 4.8,
      "stock": 25,
      "publishedYear": 2018,
      "isbn": "9780735211292",
      "image": "https://picsum.photos/seed/atomic-habits/300/450"
    },
    {
      "id": 2,
      "title": "Clean Code",
      "author": "Robert C. Martin",
      "category": "Programming",
      "price": 799,
      "rating": 4.7,
      "stock": 15,
      "publishedYear": 2008,
      "isbn": "9780132350884",
      "image": "https://picsum.photos/seed/clean-code/300/450"
    },
    {
      "id": 3,
      "title": "The Alchemist",
      "author": "Paulo Coelho",
      "category": "Fiction",
      "price": 399,
      "rating": 4.6,
      "stock": 40,
      "publishedYear": 1988,
      "isbn": "9780061122415",
      "image": "https://picsum.photos/seed/the-alchemist/300/450"
    },
    {
      "id": 4,
      "title": "Introduction to Algorithms",
      "author": "Thomas H. Cormen",
      "category": "Computer Science",
      "price": 1299,
      "rating": 4.5,
      "stock": 10,
      "publishedYear": 2009,
      "isbn": "9780262033848",
      "image": "https://picsum.photos/seed/algorithms/300/450"
    },
    {
      "id": 5,
      "title": "Think Like a Monk",
      "author": "Jay Shetty",
      "category": "Motivational",
      "price": 450,
      "rating": 4.4,
      "stock": 30,
      "publishedYear": 2020,
      "isbn": "9781982134488",
      "image": "https://picsum.photos/seed/think-like-a-monk/300/450"
    },
    {
      "id": 6,
      "title": "Rich Dad Poor Dad",
      "author": "Robert T. Kiyosaki",
      "category": "Finance",
      "price": 350,
      "rating": 4.5,
      "stock": 20,
      "publishedYear": 1997,
      "isbn": "9781612680194",
      "image": "https://picsum.photos/seed/rich-dad-poor-dad/300/450"
    },
    {
      "id": 7,
      "title": "You Don't Know JS",
      "author": "Kyle Simpson",
      "category": "Programming",
      "price": 599,
      "rating": 4.6,
      "stock": 18,
      "publishedYear": 2015,
      "isbn": "9781491904244",
      "image": "https://picsum.photos/seed/you-dont-know-js/300/450"
    },
    {
      "id": 8,
      "title": "Sapiens",
      "author": "Yuval Noah Harari",
      "category": "History",
      "price": 699,
      "rating": 4.7,
      "stock": 22,
      "publishedYear": 2011,
      "isbn": "9780062316110",
      "image": "https://picsum.photos/seed/sapiens/300/450"
    },
     {
      "id": 9,
      "title": "Atomic Habits",
      "author": "James Clear",
      "category": "Self Help",
      "price": 499,
      "rating": 4.8,
      "stock": 25,
      "publishedYear": 2018,
      "isbn": "9780735211292",
      "image": "https://picsum.photos/seed/atomic-habits/300/450"
    },
    {
      "id": 10,
      "title": "Clean Code",
      "author": "Robert C. Martin",
      "category": "Programming",
      "price": 799,
      "rating": 4.7,
      "stock": 15,
      "publishedYear": 2008,
      "isbn": "9780132350884",
      "image": "https://picsum.photos/seed/clean-code/300/450"
    },
    {
      "id": 11,
      "title": "The Alchemist",
      "author": "Paulo Coelho",
      "category": "Fiction",
      "price": 399,
      "rating": 4.6,
      "stock": 40,
      "publishedYear": 1988,
      "isbn": "9780061122415",
      "image": "https://picsum.photos/seed/the-alchemist/300/450"
    },
    {
      "id": 12,
      "title": "Introduction to Algorithms",
      "author": "Thomas H. Cormen",
      "category": "Computer Science",
      "price": 1299,
      "rating": 4.5,
      "stock": 10,
      "publishedYear": 2009,
      "isbn": "9780262033848",
      "image": "https://picsum.photos/seed/algorithms/300/450"
    },
    {
      "id": 13,
      "title": "Think Like a Monk",
      "author": "Jay Shetty",
      "category": "Motivational",
      "price": 450,
      "rating": 4.4,
      "stock": 30,
      "publishedYear": 2020,
      "isbn": "9781982134488",
      "image": "https://picsum.photos/seed/think-like-a-monk/300/450"
    },
    {
      "id": 14,
      "title": "Rich Dad Poor Dad",
      "author": "Robert T. Kiyosaki",
      "category": "Finance",
      "price": 350,
      "rating": 4.5,
      "stock": 20,
      "publishedYear": 1997,
      "isbn": "9781612680194",
      "image": "https://picsum.photos/seed/rich-dad-poor-dad/300/450"
    },
    {
      "id": 15,
      "title": "You Don't Know JS",
      "author": "Kyle Simpson",
      "category": "Programming",
      "price": 599,
      "rating": 4.6,
      "stock": 18,
      "publishedYear": 2015,
      "isbn": "9781491904244",
      "image": "https://picsum.photos/seed/you-dont-know-js/300/450"
    },
    {
      "id": 16,
      "title": "Sapiens",
      "author": "Yuval Noah Harari",
      "category": "History",
      "price": 699,
      "rating": 4.7,
      "stock": 22,
      "publishedYear": 2011,
      "isbn": "9780062316110",
      "image": "https://picsum.photos/seed/sapiens/300/450"
    },
     {
      "id": 1,
      "title": "Atomic Habits",
      "author": "James Clear",
      "category": "Self Help",
      "price": 499,
      "rating": 4.8,
      "stock": 25,
      "publishedYear": 2018,
      "isbn": "9780735211292",
      "image": "https://picsum.photos/seed/atomic-habits/300/450"
    },
    {
      "id": 2,
      "title": "Clean Code",
      "author": "Robert C. Martin",
      "category": "Programming",
      "price": 799,
      "rating": 4.7,
      "stock": 15,
      "publishedYear": 2008,
      "isbn": "9780132350884",
      "image": "https://picsum.photos/seed/clean-code/300/450"
    },
    {
      "id": 3,
      "title": "The Alchemist",
      "author": "Paulo Coelho",
      "category": "Fiction",
      "price": 399,
      "rating": 4.6,
      "stock": 40,
      "publishedYear": 1988,
      "isbn": "9780061122415",
      "image": "https://picsum.photos/seed/the-alchemist/300/450"
    },
    {
      "id": 4,
      "title": "Introduction to Algorithms",
      "author": "Thomas H. Cormen",
      "category": "Computer Science",
      "price": 1299,
      "rating": 4.5,
      "stock": 10,
      "publishedYear": 2009,
      "isbn": "9780262033848",
      "image": "https://picsum.photos/seed/algorithms/300/450"
    },
    {
      "id": 5,
      "title": "Think Like a Monk",
      "author": "Jay Shetty",
      "category": "Motivational",
      "price": 450,
      "rating": 4.4,
      "stock": 30,
      "publishedYear": 2020,
      "isbn": "9781982134488",
      "image": "https://picsum.photos/seed/think-like-a-monk/300/450"
    },
    {
      "id": 6,
      "title": "Rich Dad Poor Dad",
      "author": "Robert T. Kiyosaki",
      "category": "Finance",
      "price": 350,
      "rating": 4.5,
      "stock": 20,
      "publishedYear": 1997,
      "isbn": "9781612680194",
      "image": "https://picsum.photos/seed/rich-dad-poor-dad/300/450"
    },
    {
      "id": 7,
      "title": "You Don't Know JS",
      "author": "Kyle Simpson",
      "category": "Programming",
      "price": 599,
      "rating": 4.6,
      "stock": 18,
      "publishedYear": 2015,
      "isbn": "9781491904244",
      "image": "https://picsum.photos/seed/you-dont-know-js/300/450"
    },
    {
      "id": 8,
      "title": "Sapiens",
      "author": "Yuval Noah Harari",
      "category": "History",
      "price": 699,
      "rating": 4.7,
      "stock": 22,
      "publishedYear": 2011,
      "isbn": "9780062316110",
      "image": "https://picsum.photos/seed/sapiens/300/450"
    },
     {
      "id": 1,
      "title": "Atomic Habits",
      "author": "James Clear",
      "category": "Self Help",
      "price": 499,
      "rating": 4.8,
      "stock": 25,
      "publishedYear": 2018,
      "isbn": "9780735211292",
      "image": "https://picsum.photos/seed/atomic-habits/300/450"
    },
    {
      "id": 2,
      "title": "Clean Code",
      "author": "Robert C. Martin",
      "category": "Programming",
      "price": 799,
      "rating": 4.7,
      "stock": 15,
      "publishedYear": 2008,
      "isbn": "9780132350884",
      "image": "https://picsum.photos/seed/clean-code/300/450"
    },
    {
      "id": 3,
      "title": "The Alchemist",
      "author": "Paulo Coelho",
      "category": "Fiction",
      "price": 399,
      "rating": 4.6,
      "stock": 40,
      "publishedYear": 1988,
      "isbn": "9780061122415",
      "image": "https://picsum.photos/seed/the-alchemist/300/450"
    },
    {
      "id": 4,
      "title": "Introduction to Algorithms",
      "author": "Thomas H. Cormen",
      "category": "Computer Science",
      "price": 1299,
      "rating": 4.5,
      "stock": 10,
      "publishedYear": 2009,
      "isbn": "9780262033848",
      "image": "https://picsum.photos/seed/algorithms/300/450"
    },
    {
      "id": 5,
      "title": "Think Like a Monk",
      "author": "Jay Shetty",
      "category": "Motivational",
      "price": 450,
      "rating": 4.4,
      "stock": 30,
      "publishedYear": 2020,
      "isbn": "9781982134488",
      "image": "https://picsum.photos/seed/think-like-a-monk/300/450"
    },
    {
      "id": 6,
      "title": "Rich Dad Poor Dad",
      "author": "Robert T. Kiyosaki",
      "category": "Finance",
      "price": 350,
      "rating": 4.5,
      "stock": 20,
      "publishedYear": 1997,
      "isbn": "9781612680194",
      "image": "https://picsum.photos/seed/rich-dad-poor-dad/300/450"
    },
    {
      "id": 7,
      "title": "You Don't Know JS",
      "author": "Kyle Simpson",
      "category": "Programming",
      "price": 599,
      "rating": 4.6,
      "stock": 18,
      "publishedYear": 2015,
      "isbn": "9781491904244",
      "image": "https://picsum.photos/seed/you-dont-know-js/300/450"
    },
    {
      "id": 8,
      "title": "Sapiens",
      "author": "Yuval Noah Harari",
      "category": "History",
      "price": 699,
      "rating": 4.7,
      "stock": 22,
      "publishedYear": 2011,
      "isbn": "9780062316110",
      "image": "https://picsum.photos/seed/sapiens/300/450"
    },
     {
      "id": 1,
      "title": "Atomic Habits",
      "author": "James Clear",
      "category": "Self Help",
      "price": 499,
      "rating": 4.8,
      "stock": 25,
      "publishedYear": 2018,
      "isbn": "9780735211292",
      "image": "https://picsum.photos/seed/atomic-habits/300/450"
    },
    {
      "id": 2,
      "title": "Clean Code",
      "author": "Robert C. Martin",
      "category": "Programming",
      "price": 799,
      "rating": 4.7,
      "stock": 15,
      "publishedYear": 2008,
      "isbn": "9780132350884",
      "image": "https://picsum.photos/seed/clean-code/300/450"
    },
    {
      "id": 3,
      "title": "The Alchemist",
      "author": "Paulo Coelho",
      "category": "Fiction",
      "price": 399,
      "rating": 4.6,
      "stock": 40,
      "publishedYear": 1988,
      "isbn": "9780061122415",
      "image": "https://picsum.photos/seed/the-alchemist/300/450"
    },
    {
      "id": 4,
      "title": "Introduction to Algorithms",
      "author": "Thomas H. Cormen",
      "category": "Computer Science",
      "price": 1299,
      "rating": 4.5,
      "stock": 10,
      "publishedYear": 2009,
      "isbn": "9780262033848",
      "image": "https://picsum.photos/seed/algorithms/300/450"
    },
    {
      "id": 5,
      "title": "Think Like a Monk",
      "author": "Jay Shetty",
      "category": "Motivational",
      "price": 450,
      "rating": 4.4,
      "stock": 30,
      "publishedYear": 2020,
      "isbn": "9781982134488",
      "image": "https://picsum.photos/seed/think-like-a-monk/300/450"
    },
    {
      "id": 6,
      "title": "Rich Dad Poor Dad",
      "author": "Robert T. Kiyosaki",
      "category": "Finance",
      "price": 350,
      "rating": 4.5,
      "stock": 20,
      "publishedYear": 1997,
      "isbn": "9781612680194",
      "image": "https://picsum.photos/seed/rich-dad-poor-dad/300/450"
    },
    {
      "id": 7,
      "title": "You Don't Know JS",
      "author": "Kyle Simpson",
      "category": "Programming",
      "price": 599,
      "rating": 4.6,
      "stock": 18,
      "publishedYear": 2015,
      "isbn": "9781491904244",
      "image": "https://picsum.photos/seed/you-dont-know-js/300/450"
    },
    {
      "id": 8,
      "title": "Sapiens",
      "author": "Yuval Noah Harari",
      "category": "History",
      "price": 699,
      "rating": 4.7,
      "stock": 22,
      "publishedYear": 2011,
      "isbn": "9780062316110",
      "image": "https://picsum.photos/seed/sapiens/300/450"
    }
  ]

export default books;
